version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-news
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: news_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mcp-network

  mcp-server:
    build: .
    container_name: mcp-news-server
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/
      MONGODB_DATABASE: news_db
      MONGODB_COLLECTION: news
      SERVER_NAME: mongodb-news-mcp
      SERVER_VERSION: 1.0.0
    networks:
      - mcp-network
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
    driver: local

networks:
  mcp-network:
    driver: bridge
